const DEPARTMENT_MAP = {
	1: 'Sales',
	2: 'Procurement',
	3: 'Operations',
	4: 'Finance',
	5: 'HR',
	6: 'IT',
	7: 'Marketing',
}

const DESIGNATION_MAP = {
	1: 'Sales Manager',
	2: 'Procurement Lead',
	3: 'Operations Executive',
	4: 'Finance Analyst',
	5: 'HR Specialist',
	6: 'IT Support',
	7: 'Marketing Executive',
}

const MANAGER_MAP = {
	1: 'Rahul Mehta',
	2: 'Ananya Gupta',
	3: 'Vikram Rao',
	4: 'Priya Singh',
}

const EMPLOYMENT_TYPE_MAP = {
	1: 'Full Time',
	2: 'Contract',
	3: 'Intern',
}

// Helper function to format date to DD-MM-YYYY
const formatDate = (dateString) => {
	if (!dateString) return '';
	
	try {
		const date = new Date(dateString);
		if (isNaN(date.getTime())) return dateString;
		
		const day = String(date.getDate()).padStart(2, '0');
		const month = String(date.getMonth() + 1).padStart(2, '0');
		const year = date.getFullYear();
		
		return `${day}-${month}-${year}`;
	} catch (error) {
		return dateString;
	}
}

const FALLBACK_USERS = [
	{
		user_id: 101,
		username: 'rahul.mehta',
		email: 'rahul.mehta@rahulpapers.com',
		employee_code: 'EMP-001',
		first_name: 'Rahul',
		middle_name: '',
		last_name: 'Mehta',
		full_name: 'Rahul Mehta',
		gender: 'Male',
		date_of_birth: '12-06-1988',
		blood_group: 'B+',
		marital_status: 'Married',
		mobile_number: '+91-9876543210',
		alternate_mobile: '+91-9811122233',
		address_line1: '501, Palm Residency',
		address_line2: 'Andheri East',
		city: 'Mumbai',
		taluka: 'Andheri',
		district: 'Mumbai',
		state: 'Maharashtra',
		country: 'India',
		pin_code: '400069',
		department_id: 1,
		designation_id: 1,
		employment_type_id: 1,
		date_of_joining: '01-04-2021',
		employment_status: 'Active',
		reporting_manager_id: 3,
		profile_photo_url: '',
		is_admin: true,
		last_login_at: '30-12-2024',
		createdAt: '05-01-2024',
		updatedAt: '30-12-2024',
	},
	{
		user_id: 102,
		username: 'ananya.g',
		email: 'ananya.gupta@rahulpapers.com',
		employee_code: 'EMP-017',
		first_name: 'Ananya',
		middle_name: 'R',
		last_name: 'Gupta',
		full_name: 'Ananya R Gupta',
		gender: 'Female',
		date_of_birth: '24-02-1992',
		blood_group: 'O+',
		marital_status: 'Single',
		mobile_number: '+91-9922334455',
		alternate_mobile: '',
		address_line1: 'Shivaji Nagar',
		address_line2: 'Sector 4',
		city: 'Pune',
		taluka: 'Haveli',
		district: 'Pune',
		state: 'Maharashtra',
		country: 'India',
		pin_code: '411005',
		department_id: 2,
		designation_id: 2,
		employment_type_id: 1,
		date_of_joining: '16-08-2022',
		employment_status: 'Active',
		reporting_manager_id: 1,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '28-12-2024',
		createdAt: '16-08-2022',
		updatedAt: '28-12-2024',
	},
	{
		user_id: 103,
		username: 'vikram.rao',
		email: 'vikram.rao@rahulpapers.com',
		employee_code: 'EMP-025',
		first_name: 'Vikram',
		middle_name: '',
		last_name: 'Rao',
		full_name: 'Vikram Rao',
		gender: 'Male',
		date_of_birth: '03-11-1985',
		blood_group: 'A+',
		marital_status: 'Married',
		mobile_number: '+91-9819081908',
		alternate_mobile: '+91-9876000000',
		address_line1: 'Lake View Residency',
		address_line2: 'Sector 7',
		city: 'Ahmedabad',
		taluka: 'Daskroi',
		district: 'Ahmedabad',
		state: 'Gujarat',
		country: 'India',
		pin_code: '380015',
		department_id: 3,
		designation_id: 3,
		employment_type_id: 2,
		date_of_joining: '12-01-2020',
		employment_status: 'On Leave',
		reporting_manager_id: 4,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '15-12-2024',
		createdAt: '12-01-2020',
		updatedAt: '20-12-2024',
	},
	{
		user_id: 104,
		username: 'priya.singh',
		email: 'priya.singh@rahulpapers.com',
		employee_code: 'EMP-031',
		first_name: 'Priya',
		middle_name: '',
		last_name: 'Singh',
		full_name: 'Priya Singh',
		gender: 'Female',
		date_of_birth: '10-09-1995',
		blood_group: 'AB+',
		marital_status: 'Single',
		mobile_number: '+91-9000090000',
		alternate_mobile: '',
		address_line1: 'Green Meadows',
		address_line2: 'Phase 2',
		city: 'Surat',
		taluka: 'Surat City',
		district: 'Surat',
		state: 'Gujarat',
		country: 'India',
		pin_code: '395007',
		department_id: 4,
		designation_id: 4,
		employment_type_id: 1,
		date_of_joining: '01-03-2023',
		employment_status: 'Probation',
		reporting_manager_id: 2,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '22-12-2024',
		createdAt: '01-03-2023',
		updatedAt: '24-12-2024',
	},
	{
		user_id: 105,
		username: 'amit.patel',
		email: 'amit.patel@rahulpapers.com',
		employee_code: 'EMP-036',
		first_name: 'Amit',
		last_name: 'Patel',
		full_name: 'Amit Patel',
		gender: 'Male',
		date_of_birth: '18-01-1990',
		blood_group: 'O-',
		marital_status: 'Married',
		mobile_number: '+91-9898989898',
		address_line1: 'Navrangpura',
		address_line2: '',
		city: 'Ahmedabad',
		taluka: 'Ahmedabad City',
		district: 'Ahmedabad',
		state: 'Gujarat',
		country: 'India',
		pin_code: '380009',
		department_id: 2,
		designation_id: 2,
		employment_type_id: 1,
		date_of_joining: '19-07-2021',
		employment_status: 'Active',
		reporting_manager_id: 1,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '29-12-2024',
		createdAt: '19-07-2021',
		updatedAt: '29-12-2024',
	},
	{
		user_id: 106,
		username: 'neha.sharma',
		email: 'neha.sharma@rahulpapers.com',
		employee_code: 'EMP-042',
		first_name: 'Neha',
		last_name: 'Sharma',
		full_name: 'Neha Sharma',
		gender: 'Female',
		date_of_birth: '05-04-1993',
		blood_group: 'B-',
		marital_status: 'Single',
		mobile_number: '+91-9555512345',
		address_line1: 'H-12, Saket Apartments',
		address_line2: 'Sector 15',
		city: 'Delhi',
		taluka: 'South Delhi',
		district: 'Delhi',
		state: 'Delhi',
		country: 'India',
		pin_code: '110092',
		department_id: 5,
		designation_id: 5,
		employment_type_id: 1,
		date_of_joining: '14-02-2022',
		employment_status: 'Active',
		reporting_manager_id: 3,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '27-12-2024',
		createdAt: '14-02-2022',
		updatedAt: '27-12-2024',
	},
	{
		user_id: 107,
		username: 'rohit.verma',
		email: 'rohit.verma@rahulpapers.com',
		employee_code: 'EMP-048',
		first_name: 'Rohit',
		last_name: 'Verma',
		full_name: 'Rohit Verma',
		gender: 'Male',
		date_of_birth: '22-12-1987',
		blood_group: 'A-',
		marital_status: 'Married',
		mobile_number: '+91-9111122233',
		address_line1: '25, Vijay Nagar',
		address_line2: '',
		city: 'Indore',
		taluka: 'Indore City',
		district: 'Indore',
		state: 'Madhya Pradesh',
		country: 'India',
		pin_code: '452001',
		department_id: 3,
		designation_id: 3,
		employment_type_id: 2,
		date_of_joining: '09-09-2019',
		employment_status: 'Active',
		reporting_manager_id: 4,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '26-12-2024',
		createdAt: '09-09-2019',
		updatedAt: '26-12-2024',
	},
	{
		user_id: 108,
		username: 'sneha.nair',
		email: 'sneha.nair@rahulpapers.com',
		employee_code: 'EMP-052',
		first_name: 'Sneha',
		last_name: 'Nair',
		full_name: 'Sneha Nair',
		gender: 'Female',
		date_of_birth: '14-07-1994',
		blood_group: 'O+',
		marital_status: 'Single',
		mobile_number: '+91-9444455566',
		address_line1: 'Marine Drive Apartments',
		address_line2: 'Flat 302',
		city: 'Kochi',
		taluka: 'Kochi City',
		district: 'Ernakulam',
		state: 'Kerala',
		country: 'India',
		pin_code: '682020',
		department_id: 6,
		designation_id: 6,
		employment_type_id: 1,
		date_of_joining: '10-01-2023',
		employment_status: 'Active',
		reporting_manager_id: 2,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '25-12-2024',
		createdAt: '10-01-2023',
		updatedAt: '25-12-2024',
	},
	{
		user_id: 109,
		username: 'arjun.reddy',
		email: 'arjun.reddy@rahulpapers.com',
		employee_code: 'EMP-060',
		first_name: 'Arjun',
		last_name: 'Reddy',
		full_name: 'Arjun Reddy',
		gender: 'Male',
		date_of_birth: '01-10-1991',
		blood_group: 'B+',
		marital_status: 'Single',
		mobile_number: '+91-9000011111',
		address_line1: 'Banjara Hills',
		address_line2: 'Road No 12',
		city: 'Hyderabad',
		taluka: 'Hyderabad City',
		district: 'Hyderabad',
		state: 'Telangana',
		country: 'India',
		pin_code: '500081',
		department_id: 4,
		designation_id: 4,
		employment_type_id: 1,
		date_of_joining: '11-11-2021',
		employment_status: 'Active',
		reporting_manager_id: 1,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '24-12-2024',
		createdAt: '11-11-2021',
		updatedAt: '24-12-2024',
	},
	{
		user_id: 110,
		username: 'pooja.jain',
		email: 'pooja.jain@rahulpapers.com',
		employee_code: 'EMP-066',
		first_name: 'Pooja',
		last_name: 'Jain',
		full_name: 'Pooja Jain',
		gender: 'Female',
		date_of_birth: '30-05-1996',
		blood_group: 'AB-',
		marital_status: 'Single',
		mobile_number: '+91-9888877777',
		address_line1: 'C-Scheme',
		address_line2: 'Plot No 45',
		city: 'Jaipur',
		taluka: 'Jaipur City',
		district: 'Jaipur',
		state: 'Rajasthan',
		country: 'India',
		pin_code: '302017',
		department_id: 5,
		designation_id: 5,
		employment_type_id: 1,
		date_of_joining: '02-01-2024',
		employment_status: 'Probation',
		reporting_manager_id: 3,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '23-12-2024',
		createdAt: '02-01-2024',
		updatedAt: '23-12-2024',
	},
	{
		user_id: 111,
		username: 'manoj.yadav',
		email: 'manoj.yadav@rahulpapers.com',
		employee_code: 'EMP-071',
		first_name: 'Manoj',
		last_name: 'Yadav',
		full_name: 'Manoj Yadav',
		gender: 'Male',
		date_of_birth: '08-08-1984',
		blood_group: 'O+',
		marital_status: 'Married',
		mobile_number: '+91-9333311111',
		address_line1: 'Gomti Nagar',
		address_line2: 'Sector 7',
		city: 'Lucknow',
		taluka: 'Lucknow City',
		district: 'Lucknow',
		state: 'Uttar Pradesh',
		country: 'India',
		pin_code: '226010',
		department_id: 1,
		designation_id: 2,
		employment_type_id: 2,
		date_of_joining: '18-06-2018',
		employment_status: 'Active',
		reporting_manager_id: 4,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '22-12-2024',
		createdAt: '18-06-2018',
		updatedAt: '22-12-2024',
	},
	{
		user_id: 112,
		username: 'kavita.desai',
		email: 'kavita.desai@rahulpapers.com',
		employee_code: 'EMP-078',
		first_name: 'Kavita',
		last_name: 'Desai',
		full_name: 'Kavita Desai',
		gender: 'Female',
		date_of_birth: '27-03-1989',
		blood_group: 'A+',
		marital_status: 'Married',
		mobile_number: '+91-9222212345',
		address_line1: 'Alkapuri',
		address_line2: 'Shivaji Road',
		city: 'Vadodara',
		taluka: 'Vadodara City',
		district: 'Vadodara',
		state: 'Gujarat',
		country: 'India',
		pin_code: '390011',
		department_id: 6,
		designation_id: 6,
		employment_type_id: 1,
		date_of_joining: '05-10-2020',
		employment_status: 'Active',
		reporting_manager_id: 2,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '21-12-2024',
		createdAt: '05-10-2020',
		updatedAt: '21-12-2024',
	},
	{
		user_id: 113,
		username: 'suresh.kumar',
		email: 'suresh.kumar@rahulpapers.com',
		employee_code: 'EMP-085',
		first_name: 'Suresh',
		last_name: 'Kumar',
		full_name: 'Suresh Kumar',
		gender: 'Male',
		date_of_birth: '15-01-1982',
		blood_group: 'B+',
		marital_status: 'Married',
		mobile_number: '+91-9444412121',
		address_line1: 'T Nagar',
		address_line2: 'North Usman Road',
		city: 'Chennai',
		taluka: 'Chennai City',
		district: 'Chennai',
		state: 'Tamil Nadu',
		country: 'India',
		pin_code: '600042',
		department_id: 7,
		designation_id: 7,
		employment_type_id: 2,
		date_of_joining: '20-05-2015',
		employment_status: 'Active',
		reporting_manager_id: 4,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '20-12-2024',
		createdAt: '20-05-2015',
		updatedAt: '20-12-2024',
	},
	{
		user_id: 114,
		username: 'ritika.malhotra',
		email: 'ritika.malhotra@rahulpapers.com',
		employee_code: 'EMP-091',
		first_name: 'Ritika',
		last_name: 'Malhotra',
		full_name: 'Ritika Malhotra',
		gender: 'Female',
		date_of_birth: '11-11-1997',
		blood_group: 'O+',
		marital_status: 'Single',
		mobile_number: '+91-9777710101',
		address_line1: 'Sector 17',
		address_line2: '',
		city: 'Chandigarh',
		taluka: 'Chandigarh City',
		district: 'Chandigarh',
		state: 'Chandigarh',
		country: 'India',
		pin_code: '160036',
		department_id: 2,
		designation_id: 3,
		employment_type_id: 1,
		date_of_joining: '03-06-2024',
		employment_status: 'Probation',
		reporting_manager_id: 1,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '19-12-2024',
		createdAt: '03-06-2024',
		updatedAt: '19-12-2024',
	},
	{
		user_id: 115,
		username: 'deepak.bansal',
		email: 'deepak.bansal@rahulpapers.com',
		employee_code: 'EMP-099',
		first_name: 'Deepak',
		last_name: 'Bansal',
		full_name: 'Deepak Bansal',
		gender: 'Male',
		date_of_birth: '01-02-2026',
		blood_group: 'A+',
		marital_status: 'Married',
		mobile_number: '+91-9810012345',
		address_line1: 'DLF Phase 3',
		address_line2: '',
		city: 'Gurgaon',
		taluka: 'Gurgaon City',
		district: 'Gurgaon',
		state: 'Haryana',
		country: 'India',
		pin_code: '122018',
		department_id: 1,
		designation_id: 1,
		employment_type_id: 1,
		date_of_joining: '27-03-2017',
		employment_status: 'Active',
		reporting_manager_id: 3,
		profile_photo_url: '',
		is_admin: false,
		last_login_at: '18-12-2024',
		createdAt: '27-03-2017',
		updatedAt: '18-12-2024',
	},
];

const toDisplayUser = (user) => {
	const fullName = user.full_name || [user.first_name, user.middle_name, user.last_name]
		.filter(Boolean)
		.join(' ')

	const departmentName = user.department_name || DEPARTMENT_MAP[user.department_id]
	const designationName = user.designation_name || DESIGNATION_MAP[user.designation_id]
	const managerName = user.reporting_manager_name || MANAGER_MAP[user.reporting_manager_id]
	const employmentType = user.employment_type || EMPLOYMENT_TYPE_MAP[user.employment_type_id]

	// Format dates to DD-MM-YYYY format
	const dateOfBirth = formatDate(user.date_of_birth)
	const dateOfJoining = formatDate(user.date_of_joining)
	const lastLoginAt = formatDate(user.last_login_at)
	const createdAt = formatDate(user.createdAt)
	const updatedAt = formatDate(user.updatedAt)

	return {
		...user,
		full_name: fullName || user.username,
		department_name: departmentName,
		designation_name: designationName,
		reporting_manager_name: managerName,
		employment_type: employmentType,
		date_of_birth: dateOfBirth,
		date_of_joining: dateOfJoining,
		last_login_at: lastLoginAt,
		createdAt: createdAt,
		updatedAt: updatedAt,
	}
}

const fallbackList = () => FALLBACK_USERS.map((user) => toDisplayUser(user))

export const userApi = {
	/**
	 * Return local fallback users only (no network call while backend is unavailable).
	 */
	getAll: async () => fallbackList(),

	/**
	 * Return a single user from local fallback data.
	 */
	getById: async (id) => {
		const fallbackUser = FALLBACK_USERS.find((user) => `${user.user_id}` === `${id}`)
		return fallbackUser ? toDisplayUser(fallbackUser) : null
	},

	/**
	 * Update a user (mocked for now - updates in-memory data only)
	 */
	update: async (id, data) => {
		const userIndex = FALLBACK_USERS.findIndex((user) => `${user.user_id}` === `${id}`)
		if (userIndex === -1) throw new Error('User not found')
		
		FALLBACK_USERS[userIndex] = {
			...FALLBACK_USERS[userIndex],
			...data,
			updatedAt: new Date().toISOString(),
		}
		
		return toDisplayUser(FALLBACK_USERS[userIndex])
	},

	/**
	 * Delete a user (mocked for now - removes from in-memory data only)
	 */
	delete: async (id) => {
		const userIndex = FALLBACK_USERS.findIndex((user) => `${user.user_id}` === `${id}`)
		if (userIndex === -1) throw new Error('User not found')
		
		FALLBACK_USERS.splice(userIndex, 1)
		return { success: true }
	},
}